### ISSUE TITLE
Test data being overwritten 

### ISSUE THREAD

**Issue by Fatlog** [infertux/bashcov#29] opened 2017-10-25 13:23 UTC
Hi,

I have a bit of an odd setup for my test suite.
We use a combination of Python and Bash for our project (probably 70-80% bash scripts right now).
We are building a unit test suite retrospectively and I was looking for a tool to show us where the gaps are in our testing.
We started to build the test suite on Python as we felt it offered more features. So we have test classes that call bash scripts and check the stdout and stderr. They are run using the standard...

python -m unittest discover -s test -p '*_test.py'

This call is in a bash script called "runTests.sh" and we call it using "bashcov ./runTests.sh".
This produces a report which includes all the bash scripts even if they aren't touched by a test (which is great!). However, what seems to be happening is the results are getting nobbled as the tests progress. The only data in the report is generally the last test that ran. The coverage stats for all the other test (which have run) is 0.
Do you know if there is a way to get this working?

Thanks!

**Comment by infertux** [comment] 2017-10-25 16:12
Sounds like a duplicate of #28?

**Comment by infertux** [comment] 2017-12-28 07:41
Hey @Fatlog, I think your issue might actually be #33. Could you update to the latest version with `gem update bashcov` then try again. Please paste the output here if you're still having issues. Thanks.

**Comment by infertux** [comment] 2018-01-13 20:12
See https://github.com/infertux/bashcov/issues/28#issuecomment-357463999

**Closed by infertux** 2018-01-13 20:12 UTC
Labels: duplicate, need feedback
